apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: opni-es-direct
  namespace: cattle-logging-system
spec:
  elasticsearch:
    buffer:
      flush_interval: 30s
      flush_mode: interval
      flush_thread_count: 4
      queued_chunks_limit_size: 300
      type: file
    host: <host to ship to> #Change this to either the elasticsearch client hostname, or the address from the LoadBalancer service
    index_name: test
    log_es_400_reason: true
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: es-password
    port: 443
    scheme: https
    user: admin
    with_transporter_log: true