kibana:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod # Remove this annotation if not using cert-manager
    hosts:
    - <kibana.host.name>
    tls:
    - secretName: opni-kibana-external-ssl
      hosts:
      - <kibana.host.name>
elasticsearch:
  master:
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
  data:
    replicas: 2
    persistence:
      size: 25Gi
    javaOpts: "-Xms2g -Xmx2g"
    resources:
      limits:
        memory: 4Gi
      requests:
        memory: 4Gi
  client:
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod # Remove this annotation if not using cert-manager
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
      - opni-elastic.danbason.dev
      tls:
      - secretName: opni-elastic-external-ssl
        hosts:
        - opni-elastic.danbason.dev